# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

# define env varialbles
env:
  global:
    - NODE_VERSION: 0.12.7
    - NPM_VERSION: 3.3.6

# git configs
git:
  depth: 10

# We don't want to run linux commands as super user
sudo: false

# The platforms you wants to test against
os:
  - linux
  - osx

# Tell Travis CI we are using nodejs
# Dont define language we will install node and npm by own
# language: node_js

# Define node js version
# Dont define node version we will install node and npm by own
# node_js: 0.12


before_install:
# nvm is not yet supported on osx, will manually install
  - echo "Installing nvm and node js"
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install npm@$NPM_VERSION -g
  - node --version
  - npm --version



# Install dependency here
install:
  # Install node packages
  - npm install
  # Install bower
  - npm install bower -g
  # Install gulp
  - npm install gulp -g
  # Download bower packages
  - bower install

# We can combine them to one but
script:
    - npm run-script gulp-dist
    - npm run-script gulp-build
    - npm run-script gulp-release

after_script:
#
after_success:
#
after_failure:
#


# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# Configure email notifications
notifications:
     on_success: never
     on_failure: always


# You can delete cache using travis-ci web interface
cache:
  directories:
  - cache
  - node_modules
  - app/node_modules
  - app/bower_components
