# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

# define env vars
env:
  global:
    - NPM_VERSION: 3.9

# git configs
git:
  depth: 1

# We don't want to run linux commands as super user
sudo: false

# The platforms you wants to test against
os:
  - linux
  - osx

matrix:
  fast_finish: true

# Tell Travis CI we are using nodejs
language: node_js

# Define node js version
node_js:
  - '5'


#before_install:

# Install any dependency here
install:
  # Install node packages
  - npm set progress=false
  - npm install

# We can combine them to one but
script:
    - npm run-script gulp-dist
    - npm run-script gulp-build
    - npm run-script gulp-release

#after_script:

#after_success:

#after_failure:


# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# Configure email notifications
notifications:
     email:
        on_success: never
        on_failure: always


# You can delete cache using travis-ci web interface
cache:
  directories:
  - cache
  - node_modules
  - app/node_modules
